openapi: 3.0.0
info:
  title: MovieQuotes API
  description: MovieQuotes api routes and usage
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server

paths:
  /register-user:
    post:
      summary: Creates user.
      responses:
        "200":
          description:
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  password_confirmation:
                    type: string
                example: # Sample data
                  name: John Doe
                  email: johnny@example.com
                  password: test12345
                  password_confirmation: test12345
