openapi: 3.0.0
info:
  title: MovieQuotes API
  description: MovieQuotes api routes and usage
  version: 0.1.9

servers:
  - url: http://localhost:8000/api
    description: local server
  - url: http://producation.app/api
    description: production server

paths:
  /register:
    post:
      summary: Creates a user.
      responses:
        "201":
          description: A success message.
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  password:
                    type: string
                  password_confirmation:
                    type: string
                example: # Sample data
                  name: john doe
                  email: johnny@example.com
                  password: test12345
                  password_confirmation: test12345
        "422":
          description: Unprocessable content
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "The name format is invalid. (and 2 more errors)"
                  errors:
                    type: object
                    items:
                      type: array
                    properties:
                      name:
                        example: ["The name format is invalid."]
                      email:
                        example: ["The email must be a valid email address."]
                      password:
                        example: ["The password must be at least 8 characters."]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                password_confirmation:
                  type: string
  /login:
    post:
      summary: Authenticates a user.
      responses:
        "200":
          description: A JSON array containing the auth token
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  name:
                    type: string
                  password:
                    type: string
                # example: # Sample data
                #   access_token: "luI1Ymbfu0lo8srrXebTL7f638coXKxztjEvFml2"
                #   token_type: "bearer"
                #   expires_in: 3600
                #   username: "johndoe123"
                #   user_email: "john@gmail.com"
                #   user_id: 6
                #   user_pfp: "storage/profile-pictures/1659195277.my-picture.png"

        "401":
          description: User does not exist message
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "incorrect credentials"
        "403":
          description: Email not activated message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Check your email to activate account."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "john123"
                password:
                  type: string
                  example: "password123"
  /logout:
    post:
      summary: Logs user out.
      responses:
        "200":
          description: A JSON response with success message
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  message:
                    type: string
                    example: "Logged out successfully."
  /confirm-email:
    post:
      summary: Sends confirmation email.
      responses:
        "200":
          description: A JSON response with success message
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  message:
                    type: string
                    example: "Email confirmation sent."
        "404":
          description: A JSON response with error message
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  error:
                    type: string
                    example: "User not found"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: "johndoe@gmail.com"
  /verify-email:
    post:
      summary: Verifies user email with token
      responses:
        "200":
          description: A JSON response with success message
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  message:
                    type: string
                    example: "Email verified successfully."
        "400":
          description: Invalid token error
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  error:
                    type: string
                    example: "invalid token"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: "ce4eba3dcc2cb3ede7ba3be4b6096de1b35990de"
  /reset-password:
    patch:
      summary: Resets user password
      responses:
        "200":
          description: A JSON response with success message
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  message:
                    type: string
                    example: "Password updated successfully."
        "422":
          description: Invalid password format
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  message:
                    type: string
                    example: "The password must be at least 8 characters. (and 1 more error)"
                  errors:
                    type: object
                    items:
                      type: array
                    properties:
                      password:
                        example:
                          [
                            "The password must be at least 8 characters.",
                            "The password format is invalid.",
                          ]
        "404":
          description: User not found
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  error:
                    type: string
                    example: "User not found"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: "pass1234"
                code:
                  type: string
                  example: "ce4eba3dcc2cb3ede7ba3be4b6096de1b35990de"
  /comments:
    post:
      summary: Creates comment for a quote
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Comment created
          content:
            application/json:
              schema:
                type: object
                items:
                  type: string
                properties:
                  message:
                    example: "Comment added successfully"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quote_id:
                  type: number
                  example: 4
                body:
                  type: string
                  example: "nice quote..."
                recipient_id:
                  type: number
                  example: 5
  /all-quotes:
    get:
      summary: Returns array of quotes
      security:
        - BearerAuth: []
      responses:
        "200":
          description: A JSON array of paginated quotes
          content:
            application/json:
              schema:
                type: array

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
